baseURL: "https://yourusername.github.io/my-academic-site"
languageCode: "en-us"
title: "Your Name - Academic Website"
theme: "PaperMod"


pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Your Name"
  description: "Academic website and blog"
  keywords: [Academic, Research, Blog, Publications]
  author: "Your Name"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # home-info mode (good for academic sites)
  homeInfoParams:
    Title: "Your Name"
    Content: |
      PhD Student in [Your Field] at [University]
      
      Welcome to my academic website where I share my research and thoughts.

  # Social icons for academic profiles
  socialIcons:
    - name: github
      url: "https://github.com/yourusername"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=YOURID"
    - name: orcid
      url: "https://orcid.org/0000-0000-0000-0000"
    - name: linkedin
      url: "https://linkedin.com/in/yourusername"
    - name: email
      url: "mailto:your.email@university.edu"

  # For search functionality
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 20
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 30
    - identifier: cv
      name: CV
      url: /cv/
      weight: 40

# Syntax highlighting
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github
