baseURL: "https://wanyszka.github.io"
languageCode: "en-us"
title: Wojciech Anyszka
theme: "PaperMod"


pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: \(\mathbb{W}\text{ojciech }\mathbb{A}\text{nyszka}\)
  description: "Academic website and blog"
  keywords: [Academic, Research, Blog, Publications]
  author: "Wojciech Anyszka"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  

  profileMode:
    enabled: true
    title: <h1>\(\mathbb{W}\text{ojciech }\mathbb{A}\text{nyszka}\)</h1>  # We'll make this LaTeX-style next
    subtitle: "PhD Student at Princeton University"
    imageUrl: "/images/profile.jpeg"  # Update filename to match yours
    imageWidth: 300
    imageHeight: 300
    imageTitle: "Wojciech Anyszka"
    buttons:
      - name: About
        url: /about
      - name: Blog
        url: /posts
      - name: Publications  
        url: /publications
      - name: CV
        url: /cv
  

  # Social icons for academic profiles
  socialIcons:
    - name: github
      url: "https://github.com/wanyszka"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=EIPsNbUAAAAJ"
    - name: linkedin
      url: "https://linkedin.com/in/wojciech-anyszka"
    - name: email
      url: "mailto:wojtek.anyszka@gmail.com"

  # For search functionality
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 20
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 30
    - identifier: cv
      name: CV
      url: /cv/
      weight: 40

# Syntax highlighting
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github
  goldmark:
    renderer:
      unsafe: true
